name: Build/release

on: push

jobs:
  release:
    runs-on: windows-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 22

      - name: Build/release Electron app
        uses: Yan-Jobs/action-electron-builder@v1.7.0
        env:
          VITE_SENTRY_HOST: ${{ vars.VITE_SENTRY_HOST }}
          VITE_SENTRY_URL: ${{ vars.VITE_SENTRY_URL }}
          VITE_AUTH_HOST: ${{ vars.VITE_AUTH_HOST }}
          VITE_AUTOUPDATE_GITHUB_REPO: ${{ vars.VITE_AUTOUPDATE_GITHUB_REPO }}
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          windows_certs: ${{ secrets.windows_certs }}
          windows_certs_password: ${{ secrets.windows_certs_password }}

      - name: Create Appx Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prep-appx
          path: dist/easylauncher*.appx
          if-no-files-found: error

      - name: Create Cert Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prep-cert
          path: build/include/*
          if-no-files-found: error

      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: artifact
          pattern: prep-*
          delete-merged: true

      - name: Publish a release
        uses: softprops/action-gh-release@v2
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        with:
          make_latest: true
          body: '## Первая установка

            1. Скачайте все файлы из релиза

            2. Запустите `quickinstall.bat` от имени администратора

            3. Подтвердите установку


            ## Обновление


            1. Скачайте файл с расширением `.appx` из релиза

            2. Откройте скачанный файл

            3. Подтвердите обновление'
          files: |
            dist/easylauncher*.appx
            build/include/*
